/**
 *
 * @author Dave
 */

import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
public class CNIT255Final extends javax.swing.JFrame {





    private static CustomerAccount currentCustomer = new CustomerAccount("David", "Tang", "4/14/19", (new Address("1342 Manicott Dr", "New Yourk", "New York", "USA", "23232")), (new ContactInfo("david@gmail.com", "4315581459")), (new LoginCredentials()), "22", "22");
    private static AdminAccount adminProfile;

    private static ArrayList< ItemStock > itemStockList = new ArrayList<>();         //Holds the list of items we offer
    private static ArrayList<Supplier> supplierList = new ArrayList<>();        //Holds the list of suppliers
    private static ArrayList<Category> categoryList = new ArrayList<>();        //Holds the list of categories
    private static ArrayList< Item > cartList = new ArrayList< Item >();        //Holds the list of items in the customer's cart

    private static DefaultListModel cartModel = new DefaultListModel();

    private static double cartTotal = 0.0;
    //private static

    /**
     * Creates new form CNIT255Final
     */
    public CNIT255Final(CustomerAccount currentCust) {
        initComponents();
        currentCustomer = currentCust;

        //Lists all of our products in the jList.  jList's variable is called ProductList
        DefaultListModel productModel = new DefaultListModel();
        for (int i=0; i<itemStockList.size(); i++) {
            productModel.addElement(itemStockList.get(i).getName());
        }
        ProductList.setModel(productModel);
        
        refreshLists();
        
        
        DefaultListModel supplierModel = new DefaultListModel();
        for (int i=0; i<supplierList.size(); i++) {
            supplierModel.addElement(supplierList.get(i).getCompanyName());
        }
        jListSupplier.setModel(supplierModel);
        
        DefaultListModel categoryModel = new DefaultListModel();
        for (int i=0; i<categoryList.size(); i++) {
            categoryModel.addElement(categoryList.get(i).getCategoryName());
            System.out.println(categoryList.get(i).getCategoryName());
        }
        jListCategory.setModel(categoryModel);
        
        
        
        // Initialize cart JList
        cartJList.setModel( cartModel );

        //Creating the admin profile, needs to be in a try catch since it throws NoSuchAlgorithmException
        try
        {
            adminProfile = new AdminAccount("Joe", "Smith", "7/22/16", (new Address("8173 S. Rockland Ave.", "Downers Grove", "Illinois", "USA", "60515")), (new ContactInfo("joesmith@business.com", "6302564410")), (new LoginCredentials("admin", "1234qazw")), "A0001", "3/5/13");
        }
        catch (NoSuchAlgorithmException e)
        {
            System.out.println("Something went wrong, see: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAdminPanel = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldItemName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldItemPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldItemStock = new javax.swing.JTextField();
        jTextFieldItemExpirationDate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldItemDescription = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListSupplier = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListCategory = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButtonAddItem = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductList = new javax.swing.JList<>();
        addToCart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cartTotalText = new javax.swing.JTextField();
        purchaseCartButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        cartJList = new javax.swing.JList<>();
        clearCartButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        productQuantityList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemAdminPanel = new javax.swing.JMenuItem();

        jDialogAdminPanel.setMinimumSize(new java.awt.Dimension(700, 475));
        jDialogAdminPanel.setPreferredSize(new java.awt.Dimension(700, 475));

        jLabel5.setText("Username");

        jLabel6.setText("Password");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Name");

        jLabel8.setText("Price");

        jLabel9.setText("Stock Level");

        jLabel10.setText("Expiration Date");

        jLabel11.setText("Description");

        jListSupplier.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jListSupplier);

        jListCategory.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jListCategory);

        jLabel12.setText("Supplier");

        jLabel13.setText("Category");

        jButtonAddItem.setText("Add Item");
        jButtonAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddItemActionPerformed(evt);
            }
        });

        jMenu2.setText("File");

        jMenuItem2.setText("Exit Admin Panel");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar2.add(jMenu2);

        jDialogAdminPanel.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout jDialogAdminPanelLayout = new javax.swing.GroupLayout(jDialogAdminPanel.getContentPane());
        jDialogAdminPanel.getContentPane().setLayout(jDialogAdminPanelLayout);
        jDialogAdminPanelLayout.setHorizontalGroup(
            jDialogAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialogAdminPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogAdminPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldItemExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogAdminPanelLayout.createSequentialGroup()
                        .addGroup(jDialogAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(jDialogAdminPanelLayout.createSequentialGroup()
                                .addGroup(jDialogAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDialogAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(49, 49, 49)
                        .addGroup(jDialogAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDialogAdminPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialogAdminPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialogAdminPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldItemStock, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(37, 37, 37)
                .addGroup(jDialogAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(32, 32, 32)
                .addGroup(jDialogAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jButtonAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jDialogAdminPanelLayout.setVerticalGroup(
            jDialogAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialogAdminPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogAdminPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogAdminPanelLayout.createSequentialGroup()
                        .addGroup(jDialogAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDialogAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDialogAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldItemStock, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDialogAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldItemExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDialogAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAddItem)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ProductList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ProductList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ProductList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProductList);

        addToCart.setText("Add to Cart");
        addToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartActionPerformed(evt);
            }
        });

        jLabel1.setText("Your Cart");

        jLabel2.setText("Total:");

        cartTotalText.setEditable(false);
        cartTotalText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cartTotalText.setText("$0.00");

        purchaseCartButton.setText("Purchase Cart");
        purchaseCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseCartButtonActionPerformed(evt);
            }
        });

        cartJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(cartJList);

        clearCartButton.setText("Clear Cart");
        clearCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearCartButtonActionPerformed(evt);
            }
        });

        productQuantityList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(productQuantityList);

        jLabel3.setText("Products:");

        jLabel4.setText("Qnt:");

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItemAdminPanel.setText("Admin Panel");
        jMenuItemAdminPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdminPanelActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAdminPanel);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(addToCart)
                        .addGap(30, 30, 30)
                        .addComponent(clearCartButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(purchaseCartButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cartTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cartTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addToCart)
                    .addComponent(purchaseCartButton)
                    .addComponent(clearCartButton))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartActionPerformed
        //Adds the currently selected jList item into the 'currentCustomer's shopping cart

        String target = ProductList.getSelectedValue();

        for( int i = 0; i < itemStockList.size(); i++ )
        {
            ItemStock test = itemStockList.get( i );
            String checkName = test.getName();

            if( checkName.equals( target ))
            {
                //Checks to see if there is enough stock
                if(test.getStock() < 1) {
                    JOptionPane.showMessageDialog(this, "Item is out of stock!", "Item Out of Stock", JOptionPane.ERROR_MESSAGE);
                    break;
                }

                System.out.println("Found " + target);

                //                (No longer Relivent, using cartList ArrayList)

//                 currentCustomer.getShoppingcart().addItemToCart( (new ItemOrder(test.getIndex(), test.getName(), test.getPrice(), test.getTheSupplier(),
//                                                                    test.getExpirationDate(), test.getItemDescription(), test.getMyCategory(),
//                                                                    5)) );      //5 is the placeholder for ordernumber.

                //System.out.println("Added: " + currentCustomer.getShoppingcart().getCart().get(0).getName());
                /*
                System.out.println("Items in Cart:");
                for(ItemOrder a : currentCustomer.getShoppingcart().getCart()) {
                    System.out.println(a.getName());
                }*/

                // Change the cart list to reflect current cart changes
                cartModel.addElement( test.getName() );
                cartList.add( new Item(test.getIndex(), test.getName(), test.getPrice(), test.getTheSupplier(), //????~~
                        test.getExpirationDate(), test.getItemDescription(), test.getMyCategory() ));

                //Decreasing Stock
                itemStockList.get(i).setStock( (itemStockList.get(i).getStock() - 1) );


                // Calculate new total cart price
                String cartPrice = cartTotalText.getText().substring( 1 );
                double newCartPrice = test.getPrice() + Double.parseDouble( cartPrice );
                cartTotalText.setText( "$" + Double.toString( newCartPrice ) );

                cartTotal = newCartPrice;

                refreshLists();

                return;
            }
        }


    }//GEN-LAST:event_addToCartActionPerformed


    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);             //Exits the window
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ProductListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductListMouseClicked

    }//GEN-LAST:event_ProductListMouseClicked

    private void purchaseCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseCartButtonActionPerformed
        JDialog.setDefaultLookAndFeelDecorated( true );
        int response = JOptionPane.showConfirmDialog( null, "Would you like to purchase the cart? Total is $" + cartTotal, "Purchase confirmation",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE );

        if( response == JOptionPane.YES_OPTION )
        {
          System.out.println("Yes button clicked");
          System.out.println("Cart size: " + cartList.size());


            int cartSize = cartList.size();
            for( int i = cartSize - 1; i >= 0; i-- )
            {
                System.out.println("cartList.size(): " + cartList.size());
                System.out.println("Loop #: " + i);

                //removing 1 from the stock
                //int currentStock = itemStockList.get( (cartList.get(i).getIndex()) ).getStock();
                //itemStockList.get( (cartList.get(i).getIndex()) ).setStock(currentStock - 1);

                cartList.remove(i);
            }
            //cartList = null;
            refreshLists();

            cartModel.removeAllElements();
            cartTotalText.setText( "$0.0" );
            cartTotal = 0;

            System.out.println("Cart Size at end: " + cartList.size());
        }
    }//GEN-LAST:event_purchaseCartButtonActionPerformed

    private void clearCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearCartButtonActionPerformed
        cartModel.removeAllElements();
        cartTotalText.setText( "$0.0" );
        cartTotal = 0;

        for( int i = cartList.size() - 1; i >= 0; i-- )
        {

            //Adding items back into inventory
            int currentStock = itemStockList.get( (cartList.get(i).getIndex()) ).getStock();
            itemStockList.get( (cartList.get(i).getIndex()) ).setStock(currentStock + 1);

            //removing item from cart
            cartList.remove( i );

            System.out.println("Cart size: " + cartList.size());
            refreshLists();
        }
    }//GEN-LAST:event_clearCartButtonActionPerformed

    private void jMenuItemAdminPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdminPanelActionPerformed
        jDialogAdminPanel.setVisible(true);
        
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        
        jTextFieldItemName.setVisible(false);
        jTextFieldItemPrice.setVisible(false);
        jTextFieldItemStock.setVisible(false);
        jTextFieldItemExpirationDate.setVisible(false);
        jTextFieldItemDescription.setVisible(false);
        
        jListSupplier.setVisible(false);
        jListCategory.setVisible(false);
        
        jButtonAddItem.setVisible(false);
    }//GEN-LAST:event_jMenuItemAdminPanelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoginCredentials loginCheck = null; //Initialzed with null so Java doesnt freak out
        
        try                                 //Another try catch for catching NoSuchAlgorithmException
        {
            loginCheck = new LoginCredentials(jTextFieldUsername.getText(), new String(jPasswordField.getPassword()));
        }
        catch (NoSuchAlgorithmException e)
        {
            System.out.println("Something went wrong, see: " + e);
        }
        
        
        if((loginCheck.getUsername().equals(adminProfile.getLoginCreds().getUsername())) && (loginCheck.getPass().equals(adminProfile.getLoginCreds().getPass())))
        {
            System.out.println("bruh moment");
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);
            jLabel9.setVisible(true);
            jLabel10.setVisible(true);
            jLabel11.setVisible(true);
            jLabel12.setVisible(true);
            jLabel13.setVisible(true);
        
            jTextFieldItemName.setVisible(true);
            jTextFieldItemPrice.setVisible(true);
            jTextFieldItemStock.setVisible(true);
            jTextFieldItemExpirationDate.setVisible(true);
            jTextFieldItemDescription.setVisible(true);
        
            jListSupplier.setVisible(true);
            jListCategory.setVisible(true);
            
            jButtonAddItem.setVisible(true);
            
            jTextFieldUsername.setText("");
            jPasswordField.setText("");
        }
        else
        {
            JFrame about = new JFrame();
            JOptionPane.showMessageDialog(about, "Incorrect login credentials.\nPlease try again.");
            jPasswordField.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jTextFieldUsername.setText("");
        jPasswordField.setText("");
        jDialogAdminPanel.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButtonAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddItemActionPerformed
        JDialog.setDefaultLookAndFeelDecorated(true);
        int response = JOptionPane.showConfirmDialog( null, "Are you sure you want to add this item?", "Admin Add Itemn",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE );

        if( response == JOptionPane.YES_OPTION )
        {
        
        int supplierIndex = jListSupplier.getSelectedIndex();
        int categoryIndex = jListCategory.getSelectedIndex();
        
        itemStockList.add(new ItemStock(itemStockList.size(), jTextFieldItemName.getText(), Double.parseDouble(jTextFieldItemPrice.getText()), supplierList.get(supplierIndex), jTextFieldItemExpirationDate.getText(), jTextFieldItemDescription.getText(), categoryList.get(categoryIndex), Integer.parseInt(jTextFieldItemStock.getText())));
        
        refreshLists();
        
        System.out.println(itemStockList.size() - 1);
        System.out.println(supplierIndex);
        System.out.println(categoryIndex);
        }
    }//GEN-LAST:event_jButtonAddItemActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        System.out.println("hi guys...");




        //Initalizing Categories
        categoryList.add(new Category("Electronics", "All things electronics"));
        categoryList.add(new Category("Food", "Items which can be consumed"));
        categoryList.add(new Category("Games", "The hottest games for all platforms"));
        //Initalizing Suppliers
        supplierList.add(new Supplier("FastFit", "Ben Wagrez", (new SupplierContactInfo("fastfit@fastfit.org", "4042728293",
        "12233312", "benwagrez@fastfit.org", "7048217332", "www.fastfit.org")) ));
        supplierList.add(new Supplier("BongoCo", "Bongo Man", (new SupplierContactInfo("bongo@bongoco.com", "8085038020", "58726184", "bongoman@bongoco.com", "9498187115", "www.bongoco.com"))));


        //Initalize some Items
        itemStockList.add(new ItemStock(0,"Raspberry Pi", 35.00, supplierList.get(0), "N/A", "A tiny computer", categoryList.get(0) ,15));
        itemStockList.add(new ItemStock(1,"David's Sanityyyyy", 3301.00, supplierList.get(0), "4/16/19", "The quickly fading entity of David's Sanity", categoryList.get(1), 1));
        itemStockList.add(new ItemStock(2, "Tom Clancy's Rainbow Six: Siege", 19.99, supplierList.get(1), "N/A", "", categoryList.get(2), 500));
        itemStockList.add(new ItemStock(3, "Sid Meier’s Civilization VI", 59.99, supplierList.get(1), "N/A", "", categoryList.get(2), 700));
        itemStockList.add(new ItemStock(4, "Rocket League", 19.99, supplierList.get(1), "N/A", "", categoryList.get(2), 400));
        itemStockList.add(new ItemStock(5, "Far Cry 5", 59.99, supplierList.get(1), "N/A", "", categoryList.get(2), 700));
        itemStockList.add(new ItemStock(6, "Grand Theft Auto V", 29.99, supplierList.get(1), "N/A", "", categoryList.get(2), 200));
        itemStockList.add(new ItemStock(7, "Warframe", 0.00, supplierList.get(1), "N/A", "", categoryList.get(2), 1000));
        itemStockList.add(new ItemStock(8, "Kingdon Come: Deliverance", 39.99, supplierList.get(1), "N/A", "", categoryList.get(2), 1500));
        itemStockList.add(new ItemStock(9, "Counter-Strike: Global Offensive", 14.99, supplierList.get(1), "N/A", "", categoryList.get(2), 600));
        itemStockList.add(new ItemStock(10, "Jurassic World: Evolution", 44.99, supplierList.get(1), "N/A", "", categoryList.get(2), 800));
        itemStockList.add(new ItemStock(11, "PlayerUnknown’s Battlegrounds", 29.99, supplierList.get(1), "N/A", "", categoryList.get(2), 700));

        //itemStockList.add(e)









        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CNIT255Final(new CustomerAccount()).setVisible(true);
                //new LoginPage().setVisible(true);
            }
        });
    }

    public void refreshLists() {

        DefaultListModel productModel = new DefaultListModel();
        DefaultListModel productQuantModel = new DefaultListModel();
        for (int i=0; i<itemStockList.size(); i++) {
            productModel.addElement(itemStockList.get(i).getName());
            productQuantModel.addElement(itemStockList.get(i).getStock());
        }
        ProductList.setModel(productModel);
        productQuantityList.setModel(productQuantModel);

        // Initialize cart JList
        cartJList.setModel( cartModel );

    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ProductList;
    private javax.swing.JButton addToCart;
    private javax.swing.JList<String> cartJList;
    private javax.swing.JTextField cartTotalText;
    private javax.swing.JButton clearCartButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddItem;
    private javax.swing.JDialog jDialogAdminPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListCategory;
    private javax.swing.JList<String> jListSupplier;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemAdminPanel;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextFieldItemDescription;
    private javax.swing.JTextField jTextFieldItemExpirationDate;
    private javax.swing.JTextField jTextFieldItemName;
    private javax.swing.JTextField jTextFieldItemPrice;
    private javax.swing.JTextField jTextFieldItemStock;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JList<String> productQuantityList;
    private javax.swing.JButton purchaseCartButton;
    // End of variables declaration//GEN-END:variables
}
